# Generated by Django 3.2.6 on 2021-08-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_rating_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default='o', max_digits=4),
        ),
    ]
