# Generated by Django 3.2.6 on 2021-08-24 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awname', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.db.models.fields.DateTimeField)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(default=django.db.models.fields.DateTimeField)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('language', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('artists', models.ManyToManyField(to='review.Artist')),
                ('awards', models.ManyToManyField(to='review.Award')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.IntegerField(max_length=50)),
                ('votes', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.movie')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='awards_receieve',
            field=models.ManyToManyField(to='review.Award'),
        ),
    ]
