# Generated by Django 3.2.6 on 2021-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_rating',
            field=models.IntegerField(),
        ),
    ]
