# Generated by Django 3.2.6 on 2021-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_movie_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
        ),
    ]
