# Generated by Django 3.2.6 on 2021-08-31 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210830_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='PDF',
        ),
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(default='*', upload_to='content', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
