# Generated by Django 3.2.6 on 2021-08-31 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210831_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc',
        ),
        migrations.AddField(
            model_name='document',
            name='PDF',
            field=models.FileField(default='settings.MEDIA_ROOT/pdf_file/dummy.pdf', upload_to='pdf_file', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
