# Generated by Django 3.2.6 on 2021-08-31 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_document_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
