# Generated by Django 3.2.6 on 2021-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_track', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Education', 'Education'), ('Gifts & Donations', 'Gifts & Donations'), ('Investments', 'Investments'), ('Bills & Utilities', 'Bills & Utilities'), ('Food & Dining', 'Food & Dining'), ('Health & Fitness', 'Health & Fitness'), ('Personal Care', 'Personal Care'), ('Fees & Charges', 'Fees & Charges'), ('Others', 'Others')], default='*', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
